// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
  }
}
