/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import type { StackProps } from 'aws-cdk-lib';
import { Stack } from 'aws-cdk-lib';
import { BuildSpec, ComputeType } from 'aws-cdk-lib/aws-codebuild';
import { Repository } from 'aws-cdk-lib/aws-codecommit';
import type { IFileSetProducer } from 'aws-cdk-lib/pipelines';
import { CodeBuildStep, CodePipeline, CodePipelineSource } from 'aws-cdk-lib/pipelines';
import { NagSuppressions } from 'cdk-nag';
import type { Construct } from 'constructs';

const DEFAULT_BRANCH_NAME = 'main';
const SYNTH_DIRECTORY = 'packages/threat-composer-infra/cdk.out';

/**
 * CI/CD pipeline for the Threat Composer website.
 *
 * This replaces `@aws/pdk`'s `PDKPipeline` / `PDKPipelineWithCodeConnection`
 * with the CDK's own `pipelines.CodePipeline`. The Sonar code scanner that
 * PDKPipeline could attach (`sonarqubeScannerConfig` context) is not carried
 * over; add a `CodeBuildStep` to `post` if that is needed again.
 */
export class PipelineStack extends Stack {
  readonly pipeline: CodePipeline;

  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const useCodeConnection = String(this.node.tryGetContext('useCodeConnection')) === 'true';
    const repositoryName = this.node.tryGetContext('repositoryName') || 'threat_composer_monorepo';
    const repositoryOwnerAndName = this.node.tryGetContext('repositoryOwnerAndName');
    const codeConnectionArn = this.node.tryGetContext('codeConnectionArn');
    const branchName = this.node.tryGetContext('defaultBranchName') || DEFAULT_BRANCH_NAME;

    let source: IFileSetProducer;

    if (useCodeConnection) {
      if (!repositoryOwnerAndName || !codeConnectionArn) {
        throw new Error(
          'useCodeConnection requires both the repositoryOwnerAndName and codeConnectionArn context values.',
        );
      }

      source = CodePipelineSource.connection(repositoryOwnerAndName, branchName, {
        connectionArn: codeConnectionArn,
      });
    } else {
      const repository = new Repository(this, 'CodeRepository', {
        repositoryName,
        description: 'Threat Composer monorepo',
      });

      source = CodePipelineSource.codeCommit(repository, branchName);
    }

    this.pipeline = new CodePipeline(this, 'ApplicationPipeline', {
      publishAssetsInParallel: false,
      crossAccountKeys: true,
      codeBuildDefaults: {
        buildEnvironment: {
          computeType: ComputeType.LARGE,
        },
        partialBuildSpec: BuildSpec.fromObject({
          phases: {
            install: {
              'runtime-versions': {
                nodejs: '20.x',
              },
            },
          },
        }),
      },
      synth: new CodeBuildStep('Synth', {
        input: source,
        installCommands: ['yarn install --frozen-lockfile --check-files'],
        commands: ['yarn build'],
        primaryOutputDirectory: SYNTH_DIRECTORY,
      }),
    });
  }

  /**
   * Suppress cdk-nag findings on the CI/CD scaffolding that `CodePipeline`
   * generates for itself. PDKPipeline applied the equivalent suppressions
   * internally.
   *
   * Must be called after `pipeline.buildPipeline()`, because the roles and
   * policies these findings refer to do not exist until the pipeline is built.
   * Scoped to the pipeline construct rather than the stack, so anything else
   * added to this stack is still evaluated.
   */
  public suppressPipelineNagFindings() {
    NagSuppressions.addResourceSuppressions(
      this.pipeline,
      [
        {
          id: 'AwsSolutions-IAM5',
          reason:
            'Roles are generated by the CDK CodePipeline construct. The wildcards are inherent to it: '
            + 'asset publishing and self-mutation must reach CloudFormation, CodeBuild report groups and '
            + 'log streams whose names are only known at execution time, and cross-account deploy roles '
            + 'are assumed by path.',
        },
        {
          id: 'AwsSolutions-KMS5',
          reason:
            'The artifact bucket KMS key is created and managed by the CDK CodePipeline construct, which '
            + 'does not expose key rotation configuration.',
        },
        {
          id: 'AwsSolutions-S1',
          reason:
            'The pipeline artifact bucket is created and managed by the CDK CodePipeline construct. It '
            + 'holds only build artifacts, and server access logging is not configurable on it.',
        },
      ],
      true,
    );
  }
}
