// Generated by wxt
export {}
declare global {
  const __MANIFEST_VERSION__: 2 | 3;
  const __BROWSER__: string;
  const __IS_CHROME__: boolean;
  const __IS_FIREFOX__: boolean;
  const __IS_SAFARI__: boolean;
  const __IS_EDGE__: boolean;
  const __IS_OPERA__: boolean;
  const __COMMAND__: "build" | "serve";
  const __ENTRYPOINT__: string;
}
