// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/content-script.js"
    | "/popup.html"
    | "/scriptInjectForCodeCatalyst.js"
    | "/scriptInjectForThreatComposer.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
