// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-script.js"
    | "/icon-128.png"
    | "/icons/128.png"
    | "/icons/16.png"
    | "/icons/32.png"
    | "/icons/48.png"
    | "/popup.html"
    | "/scriptInjectForCodeCatalyst.js"
    | "/scriptInjectForThreatComposer.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
